#!/usr/bin/env node
// Resync Hermes agent offers: delete + recreate with maxSeconds 60.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BASE = process.env.BASE || "http://127.0.0.1:3010";
const state = JSON.parse(readFileSync(path.join(__dirname, "state.json"), "utf8"));

const CAPABILITIES = [
  { capability: "text.reply",   title: "Hermes Instant Reply",       price: 0.10, desc: "Helpful, direct replies generated by Hermes Agent (Nous Research)." },
  { capability: "text.summarize", title: "Hermes Summarizer",        price: 0.15, desc: "Concise summaries of long text by Hermes Agent." },
  { capability: "text.translate", title: "Hermes Translator",        price: 0.15, desc: "Translation to a target language by Hermes Agent." },
  { capability: "agent.answer", title: "Hermes Q&A",                 price: 0.10, desc: "Concise answers to questions by Hermes Agent." },
  { capability: "llm.complete", title: "Hermes Completion",          price: 0.10, desc: "General LLM completion by Hermes Agent." },
  { capability: "code.review",  title: "Hermes Code Review",         price: 0.50, desc: "Structured code review (bugs, security, perf) by Hermes Agent." },
  { capability: "hermes.task",  title: "Hermes Autonomous Task",     price: 1.00, desc: "Full autonomous task execution with tools (terminal, files, web) by Hermes Agent. 60s budget." },
];

async function api(pathname, opts = {}) {
  const r = await fetch(`${BASE}${pathname}`, { headers: { "content-type": "application/json", ...(opts.headers || {}) }, ...opts });
  const j = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(`${pathname} → ${r.status}: ${JSON.stringify(j).slice(0, 200)}`);
  return j;
}

async function main() {
  for (const c of CAPABILITIES) {
    const oldId = state.offerIds[c.capability];
    if (oldId) {
      try { await api(`/api/v1/offers/${oldId}`, { method: "DELETE", headers: { "x-api-key": state.apiKey } }); console.log(`🗑  deleted ${c.capability}: ${oldId}`); }
      catch (e) { console.log(`⚠️  delete ${c.capability} failed (continuing): ${e.message}`); }
    }
    const o = await api("/api/v1/offers", {
      method: "POST",
      headers: { "x-api-key": state.apiKey },
      body: JSON.stringify({
        capability: c.capability,
        title: c.title,
        description: c.desc,
        priceAmount: c.price,
        priceAsset: "HBAR",
        fulfillmentType: "webhook",
        maxSeconds: 60,
        tags: ["hermes", c.capability.split(".")[1]],
      }),
    });
    state.offerIds[c.capability] = o.offer?.id || o.id;
    console.log(`✅ recreated ${c.capability}: ${state.offerIds[c.capability]} @ ${c.price} HBAR (maxSeconds 60)`);
  }
  writeFileSync(path.join(__dirname, "state.json"), JSON.stringify(state, null, 2), { mode: 0o600 });
  console.log("state.json updated");
}

main().catch((e) => { console.error("FATAL:", e.message); process.exit(1); });
