#!/usr/bin/env node
/**
 * Hermes Agent — AgentBazaar Seller
 *
 * Registers itself on AgentBazaar (agentbazaar.app) and fulfills orders
 * by running the real Hermes agent (full tool access) via `hermes chat -q`.
 *
 * Flow:
 *   1. On boot: if state.json missing → POST /api/v1/agents/register
 *      (name, wallet, webhookUrl, capabilities, telegramChatId)
 *      then POST /api/v1/offers for each capability → save state.json
 *   2. Serve POST /webhook: marketplace sends fulfillment_request
 *      { orderId, offerId, capability, input, timestamp }
 *   3. Build a capability-specific prompt, run `hermes chat -q` (50s cap),
 *      return { ok, result, <capability field> } as JSON — that becomes the buyer's result.
 *
 * Marketplace waits max 60s for the webhook response (clamped).
 * Logs every order to orders.jsonl.
 *
 * Env:
 *   PORT                 (default 3014)
 *   MARKETPLACE_URL      (default http://127.0.0.1:3010 — use https://agentbazaar.app for prod)
 *   PUBLIC_URL           (default http://187.55.228.127:3014 — must be public, SSRF-checked)
 *   WALLET_ACCOUNT_ID    (default 0.0.9587214 — operator, testnet)
 *   TELEGRAM_CHAT_ID     (default 429384890 — order notifications)
 *   HERMES_BIN           (default hermes)
 *   HERMES_PROMPT_PREFIX (default "" — extra instruction prepended to every prompt)
 *   MAX_LLM_SECONDS      (default 50 — hard cap; marketplace allows 60)
 */
import http from "node:http";
import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, appendFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Config ───
const PORT = Number(process.env.PORT || 3014);
const MARKETPLACE_URL = process.env.MARKETPLACE_URL || "http://127.0.0.1:3010";
const PUBLIC_URL = process.env.PUBLIC_URL || "http://187.55.228.127:3014";
const WALLET_ACCOUNT_ID = process.env.WALLET_ACCOUNT_ID || "0.0.9587214";
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID || "429384890";
const HERMES_BIN = process.env.HERMES_BIN || "hermes";
const HERMES_PROMPT_PREFIX = process.env.HERMES_PROMPT_PREFIX || "You are Hermes Agent (Nous Research), fulfilling a paid order on the AgentBazaar marketplace. Be direct, professional and concise. Respond in the same language as the buyer's input unless the task explicitly asks otherwise.";
const MAX_LLM_SECONDS = Number(process.env.MAX_LLM_SECONDS || 52);

const STATE_FILE = path.join(__dirname, "state.json");
const ORDERS_LOG = path.join(__dirname, "orders.jsonl");

// Capabilities this seller offers (each maps to a Hermes prompt template)
const CAPABILITIES = [
  { capability: "text.reply",   title: "Hermes Instant Reply",       price: 0.10, desc: "Helpful, direct replies generated by Hermes Agent (Nous Research)." },
  { capability: "text.summarize", title: "Hermes Summarizer",        price: 0.15, desc: "Concise summaries of long text by Hermes Agent." },
  { capability: "text.translate", title: "Hermes Translator",        price: 0.15, desc: "Translation to a target language by Hermes Agent." },
  { capability: "agent.answer", title: "Hermes Q&A",                 price: 0.10, desc: "Concise answers to questions by Hermes Agent." },
  { capability: "llm.complete", title: "Hermes Completion",          price: 0.10, desc: "General LLM completion by Hermes Agent." },
  { capability: "code.review",  title: "Hermes Code Review",         price: 0.50, desc: "Structured code review (bugs, security, perf) by Hermes Agent." },
  { capability: "hermes.task",  title: "Hermes Autonomous Task",     price: 1.00, desc: "Full autonomous task execution with tools (terminal, files, web) by Hermes Agent. 50s budget." },
];

// ─── State ───
let state = { agentId: null, apiKey: null, offerIds: {} };
if (existsSync(STATE_FILE)) {
  try { state = { ...state, ...JSON.parse(readFileSync(STATE_FILE, "utf8")) }; } catch {}
}
let stats = { fulfilled: 0, errors: 0, timeouts: 0, uptime: Date.now() };
let queue = Promise.resolve(); // serialize fulfillment runs

// ─── Helpers ───
function saveState() {
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), { mode: 0o600 });
}
function logOrder(entry) {
  try { appendFileSync(ORDERS_LOG, JSON.stringify({ ...entry, at: new Date().toISOString() }) + "\n"); } catch {}
}
async function api(pathname, opts = {}) {
  const resp = await fetch(`${MARKETPLACE_URL}${pathname}`, {
    headers: { "content-type": "application/json", ...(opts.headers || {}) },
    ...opts,
  });
  const j = await resp.json().catch(() => ({}));
  if (!resp.ok) throw new Error(`${opts.method || "GET"} ${pathname} → ${resp.status}: ${JSON.stringify(j).slice(0, 300)}`);
  return j;
}

// ─── Registration ───
async function register() {
  console.log("[hermes-bot] Registering on AgentBazaar...");
  const reg = await api("/api/v1/agents/register", {
    method: "POST",
    body: JSON.stringify({
      name: "Hermes Agent",
      description: "Hermes Agent by Nous Research — autonomous agent with full tool access (terminal, files, web, skills).",
      walletAccountId: WALLET_ACCOUNT_ID,
      webhookUrl: `${PUBLIC_URL}/webhook`,
      capabilities: CAPABILITIES.map((c) => c.capability),
      homepage: "https://github.com/NousResearch/hermes-agent",
      telegramChatId: TELEGRAM_CHAT_ID,
      policy: { dailySpendLimit: 50, maxPerTx: 5 },
    }),
  });
  state.agentId = reg.agentId;
  state.apiKey = reg.apiKey;
  console.log(`[hermes-bot] ✅ Registered: ${reg.agentId}`);

  for (const c of CAPABILITIES) {
    const o = await api("/api/v1/offers", {
      method: "POST",
      headers: { "x-api-key": state.apiKey },
      body: JSON.stringify({
        capability: c.capability,
        title: c.title,
        description: c.desc,
        priceAmount: c.price,
        priceAsset: "HBAR",
        fulfillmentType: "webhook",
        maxSeconds: 60,
        tags: ["hermes", c.capability.split(".")[1]],
      }),
    });
    state.offerIds[c.capability] = o.offer?.id || o.id;
    console.log(`[hermes-bot] ✅ Offer ${c.capability}: ${state.offerIds[c.capability]} @ ${c.price} HBAR`);
  }
  saveState();
}

// ─── Hermes run ───
const ERROR_PATTERNS = [
  /API call failed after \d+ retries/i,
  /No available channel for model/i,
  /HTTP 50\d/i,
  /rate\s*limit/i,
  /upstream request timeout/i,
  /model.*(?:unavailable|not found|does not exist)/i,
];
function looksLikeError(text) {
  return ERROR_PATTERNS.some((re) => re.test(text));
}
function cleanChildEnv() {
  const env = { ...process.env, HERMES_NONINTERACTIVE: "1" };
  // Remove provider env vars so the child uses config.yaml providers only
  for (const k of Object.keys(env)) {
    if (/^TOKENROUTER_|^LLM_|^OPENAI_|^ANTHROPIC_|^GOOGLE_/i.test(k)) delete env[k];
  }
  return env;
}
function runHermesOnce(prompt, timeoutSeconds = MAX_LLM_SECONDS) {
  return new Promise((resolve) => {
    const t0 = Date.now();
    const args = ["chat", "-Q", "-q", prompt];
    const child = spawn(HERMES_BIN, args, {
      env: cleanChildEnv(),
      timeout: timeoutSeconds * 1000,
    });
    let out = "";
    let err = "";
    const timer = setTimeout(() => {
      try { child.kill("SIGKILL"); } catch {}
    }, timeoutSeconds * 1000);

    child.stdout.on("data", (d) => { out += d.toString(); if (out.length > 180_000) out = out.slice(0, 180_000); });
    child.stderr.on("data", (d) => { err += d.toString(); if (err.length > 20_000) err = err.slice(0, 20_000); });
    child.on("error", (e) => { clearTimeout(timer); resolve({ ok: false, error: e.message, latencyMs: Date.now() - t0 }); });
    child.on("close", (code) => {
      clearTimeout(timer);
      const latencyMs = Date.now() - t0;
      const raw = (out || "").trim();
      let text = raw;
      if (text) {
        // Strip programmatic-mode footer (session_id: …) and Query echo
        text = raw
          .split("\n")
          .filter((l) => !/^\s*session_id\s*:/i.test(l.trim()))
          .join("\n")
          .trim();
      }
      if (code !== 0 && !text) {
        resolve({ ok: false, error: `hermes exited ${code}: ${(err || "").slice(-500)}`, latencyMs });
      } else if (!text) {
        resolve({ ok: false, error: "empty response", latencyMs });
      } else if (looksLikeError(text)) {
        resolve({ ok: false, error: `model/provider error surfaced as output: ${text.slice(0, 300)}`, latencyMs });
      } else {
        resolve({ ok: true, text, latencyMs });
      }
    });
  });
}
function runHermes(prompt) {
  // One retry for transient provider failures — budget-aware so the total
  // (attempt 1 + backoff + attempt 2) always fits under the marketplace
  // webhook timeout (offer.maxSeconds, currently 60).
  const MARKET_BUDGET_SECONDS = 60;
  const OVERHEAD_SECONDS = 4;
  const t0 = Date.now();
  return runHermesOnce(prompt).then((r) => {
    if (!r.ok && r.error?.startsWith("model/provider error")) {
      const elapsed = Date.now() - t0;
      const remaining = MARKET_BUDGET_SECONDS - elapsed - OVERHEAD_SECONDS;
      if (remaining >= 15) {
        const secondCap = Math.min(MAX_LLM_SECONDS, remaining);
        return new Promise((resolve) => setTimeout(() => resolve(runHermesOnce(prompt, secondCap)), 1000));
      }
    }
    return r;
  });
}

// ─── Prompt builders ───
function buildPrompt(capability, input) {
  const s = (v) => (v == null ? "" : String(v));
  let user = "";
  switch (capability) {
    case "text.summarize":
      user = `Summarize the following text concisely. Output only the summary, no preamble.\n\nTEXT:\n${s(input?.text || input?.content || input)}`.slice(0, 15000);
      break;
    case "text.translate": {
      const target = s(input?.targetLang || input?.language || "en");
      user = `Translate the following text to ${target}. Output only the translation, no preamble.\n\nTEXT:\n${s(input?.text || input?.sourceText || input?.content || input)}`.slice(0, 15000);
      break;
    }
    case "text.reply":
      user = `Reply helpfully and directly to the following message. Output only your reply.\n\nMESSAGE:\n${s(input?.text || input?.message || input)}`.slice(0, 12000);
      break;
    case "agent.answer":
      user = `Answer the following question directly and concisely. If you don't know, say so. Output only the answer.\n\nQUESTION:\n${s(input?.question || input?.text || input)}`.slice(0, 12000);
      break;
    case "llm.complete":
      user = `Complete the following. Output only the result.\n\nINPUT:\n${s(input?.prompt || input?.text || input)}`.slice(0, 12000);
      break;
    case "code.review":
      user = `Review the following code for bugs, security issues, performance problems, and best-practice violations. Output a structured review with severity labels (CRITICAL/HIGH/MEDIUM/LOW) and suggested fixes. You have a tight time budget (~45 seconds): prefer direct analysis; if you use tools, keep it to at most one quick check.\n\nCODE:\n${s(input?.code || input?.text || input)}`.slice(0, 15000);
      break;
    case "hermes.task":
      user = `You are Hermes, an autonomous agent running on the AgentBazaar marketplace. Execute the following task using your tools (terminal, files, web search, etc.). You have a very limited time budget (~50 seconds). Do the most important part of the task, then report the result concisely.\n\nTASK:\n${s(input?.task || input?.description || input)}`.slice(0, 8000);
      break;
    default:
      user = `Handle the following request and output the result.\n\nREQUEST:\n${s(input?.text || input)}`.slice(0, 12000);
  }
  return (HERMES_PROMPT_PREFIX ? HERMES_PROMPT_PREFIX + "\n\n" : "") + user;
}

// ─── Fulfillment ───
async function fulfill(payload) {
  const { orderId, offerId, capability, input } = payload;
  const t0 = Date.now();
  try {
    const prompt = buildPrompt(capability || "text.reply", input || {});
    const run = await runHermes(prompt);
    const latencyMs = Date.now() - t0;
    if (!run.ok) {
      stats.errors++;
      logOrder({ orderId, offerId, capability, ok: false, error: run.error, latencyMs });
      return { status: 500, json: { ok: false, error: run.error, orderId, capability } };
    }
    stats.fulfilled++;
    logOrder({ orderId, offerId, capability, ok: true, chars: run.text.length, latencyMs });
    const field = capability === "text.summarize" ? "summary"
      : capability === "text.translate" ? "translation"
      : capability === "code.review" ? "review"
      : capability === "agent.answer" ? "answer"
      : capability === "text.reply" ? "reply"
      : "result";
    return {
      status: 200,
      json: {
        ok: true,
        orderId,
        offerId,
        capability,
        fulfilledBy: "hermes-agent",
        [field]: run.text,
        result: run.text,
        latencyMs,
        at: new Date().toISOString(),
      },
    };
  } catch (e) {
    stats.errors++;
    logOrder({ orderId, offerId, capability, ok: false, error: e.message, latencyMs: Date.now() - t0 });
    return { status: 500, json: { ok: false, error: e.message, orderId, capability } };
  }
}

// ─── HTTP server ───
const server = http.createServer(async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, X-OpenMarket-*");
  if (req.method === "OPTIONS") { res.writeHead(200); res.end(); return; }

  // Health
  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({
      ok: true,
      agent: "Hermes Agent",
      agentId: state.agentId,
      offers: state.offerIds,
      apiKeySet: !!state.apiKey,
      uptimeSec: Math.floor((Date.now() - stats.uptime) / 1000),
      stats,
    }));
    return;
  }

  // Webhook fulfillment
  if (req.method === "POST" && (req.url === "/webhook" || req.url === "/")) {
    const chunks = [];
    for await (const c of req) chunks.push(c);
    const raw = Buffer.concat(chunks).toString("utf8");
    let payload = {};
    try { payload = JSON.parse(raw || "{}"); } catch {}
    const event = req.headers["x-openmarket-event"] || payload.event;
    const orderId = req.headers["x-openmarket-order-id"] || payload.orderId;

    if (event !== "fulfillment_request" && !orderId && !payload.capability) {
      res.writeHead(400, { "content-type": "application/json" });
      res.end(JSON.stringify({ ok: false, error: "not a fulfillment request" }));
      return;
    }

    console.log(`[hermes-bot] ⚡ fulfillment_request order=${orderId} cap=${payload.capability || "?"}`);
    // Serialize to keep latency predictable
    queue = queue.then(() => fulfill(payload)).catch((e) => ({ status: 500, json: { ok: false, error: e.message } }));
    const result = await queue;
    res.writeHead(result.status, { "content-type": "application/json" });
    res.end(JSON.stringify(result.json));
    return;
  }

  res.writeHead(404, { "content-type": "application/json" });
  res.end(JSON.stringify({ ok: false, error: "not found" }));
});

// ─── Main ───
async function main() {
  server.listen(PORT, "0.0.0.0", async () => {
    console.log(`[hermes-bot] 🚀 Hermes Agent seller listening on 0.0.0.0:${PORT}`);
    console.log(`[hermes-bot] Webhook URL: ${PUBLIC_URL}/webhook`);
    if (!state.apiKey) {
      try {
        await register();
      } catch (e) {
        console.error(`[hermes-bot] ❌ Registration failed: ${e.message}`);
        console.error(`[hermes-bot] Will retry registration on next boot (state.json not written).`);
      }
    } else {
      console.log(`[hermes-bot] Already registered: ${state.agentId} (apiKey set)`);
    }
    console.log(`[hermes-bot] Ready. Waiting for orders...`);
  });
}

main().catch((e) => { console.error("[hermes-bot] Fatal:", e); process.exit(1); });
